redis-ha:
  enabled: true
controller:
  enableStatefulSet: true
server:
  replicas: 1
  ingress:
    enabled: true
    annotations: 
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      cert-manager.io/issuer: letsencrypt-nginx-argocd
    ingressClassName: "nginx"
    hosts:
      - argocd.sendi.bcxos.com
    tls:
      - secretName: argocd-secret
        hosts:
          - argocd.sendi.bcxos.com
  env:
    - name: ARGOCD_API_SERVER_REPLICAS
      value: '1'
configs:
  params:
    server.insecure: true
repoServer:
  replicas: 1
