apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-nginx-grafana
  namespace: prometheus
spec:
  acme:
    email: sendi@bcxstudio.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-nginx-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
