apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: {{ .Values.metadata.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: jetstack/cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: {{ .Values.certManager.version}}
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        prometheus:
          enabled: false
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # create destination namespace if not present
