{{ if .Values.nats.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.nats.name}}
  namespace: {{ .Values.metadata.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: nats
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    targetRevision: {{ .Values.nats.version}}
    helm:
      releaseName: {{ .Values.nats.name}}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.nats.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # create destination namespace if not present
{{ end }}